- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    npm test
  displayName: 'Run tests'
  
- script: |
    npm run build
  displayName: 'Build for production'