const express = require('express');
const router = express.Router();
const authController = require('../controllers/authController');
const dashboardController = require('../controllers/dashboardController');
const { authenticateToken } = require('../middleware/auth');
router.post('/register', authController.register);
router.post('/login', authController.login);
router.post('/logout', authController.logout);
router.get('/protectedcust',authenticateToken, dashboardController.protected);
module.exports = router;